package com.cristiano.galactic.model.enums;

public enum ControlEnum {
	CTL_TURN_LEFT,
	CTL_TURN_RIGHT,
	CTL_MOVE_LEFT,
	CTL_MOVE_RIGHT,
	CTL_MOVE_UP,
	CTL_MOVE_DOWN,
	CTL_TURN_UP,
	CTL_TURN_DOWN,
	CTL_ROLL_LEFT,
	CTL_ROLL_RIGHT,
	CTL_ENGINE_INC,
	CTL_ENGINE_DEC,
	CTL_ENGINE_MAX,
	CTL_ENGINE_STOP,
	CTL_WEAPON,
	CTL_LASER 
}
